apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: mdhack/solar-system:1-73a0c9dd1d103d575a07dc8ac445cc09c5b6c82a
        name: solar-system
        ports: 
        - containerPort: 80
