apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: solar-system
  name: solar-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-system
  strategy: {}
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - image: mdhack/solar-system:2-381719107734fec2917d809fe9ef8c0fd654e661
        name: solar-system
        ports: 
        - containerPort: 80
